server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    dsn: "root:zengyuan@tcp(home.007666.xyz:3306)/realworld?charset=utf8mb4&parseTime=True&loc=Local"
