spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://home.007666.xyz:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC